### ISSUE TITLE
Can't retrieve informations

### ISSUE THREAD

**Issue by nlamirault** [StaticCube/python-synology#2]
Hi try to use your library like in the example : 

```
python syno.py 
Creating Valid API
=== Utilisation ===
CPU Load:   None %
Memory Use: None %
Net Up:     None
Net Down:   None
=== Storage ===
Traceback (most recent call last):
  File "syno.py", line 14, in <module>
    for volume in volumes:
TypeError: 'NoneType' object is not iterable
(venv)iMac:venv sophie$ vi syno.py
(venv)iMac:venv sophie$ python syno.py 
Creating Valid API
=== Utilisation ===
CPU Load:   None %
Memory Use: None %
Net Up:     None
Net Down:   None
=== Storage ===
Traceback (most recent call last):
  File "syno.py", line 14, in <module>
    for volume in volumes:
TypeError: 'NoneType' object is not iterable
```

with value :  

```
api = SynologyDSM("192.168.1.13", "5000", "xxxx", "xxxxx")
```

Any idea ?

**Comment by StaticCube** [comment]
Hi, interesting please make sure the user has sufficient rights (or try with an Admin account). 

Also which version  of DSM are you using?

**Comment by nlamirault** [comment]
version : DSM 6.1.3-15152 Update 3
My user "nicolas" is in the "admin" group. "admin" user is disabled on my Synology.

**Comment by StaticCube** [comment]
Thanks noticed I did not update my system yet so will do so and try to reproduce the issue, will get back to you.

**Comment by nlamirault** [comment]
I just have a test in DEBUG mode:

```python
>>> api = SynologyDSM("192.168.1.13","5000", "xxxxxx", "xxxxxxxxxxx", True)
>>> api.utilisation
DEBUG: Creating New Session
DEBUG: Requesting URL: 'http://192.168.1.13:5000/webapi/auth.cgi?api=SYNO.API.Auth&version=2&method=login&account=xxxxxxx&passwd=xxxxxx&session=Core&format=cookie'
DEBUG: Request executed: 200
DEBUG: Failed: {"error":{"code":402},"success":false}

DEBUG: Authentication Failed
DEBUG: Login Failed, unable to process request
<SynologyDSM.SynologyDSM.SynoUtilization object at 0x7f33f1976cc0>
```

i search in Github **SYNO.API.Auth**, and i find some code from Synology in Openstack Cinder : https://github.com/openstack/cinder/blob/master/cinder/volume/drivers/synology/synology_common.py

But this API use OTP authentication.

**Comment by nlamirault** [comment]
OK. I try with another user it works. I've got two-factor authentication enabled for this user. Sorry for noise.

**Comment by StaticCube** [comment]
No problem i will update the documentation to indicate 2 factor should be turned off (was going crazy not being able to reproduce this :-))
