### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by PRabahy** [StaticCube/python-synology#5]
https://github.com/StaticCube/python-synology/blob/master/SynologyDSM/SynologyDSM.py#L389 has "http" hardcoded. It would be nice if we could use HTTPS instead. I just tested accessing https://MYIP:5001/webapi/auth.cgi?api=SYNO.API.Auth&version=2 in my webbrowser and got an identical response as going to http://MYIP:5000/webapi/auth.cgi?api=SYNO.API.Auth&version=2.

**Comment by PRabahy** [comment]
Oops, I didn't realize there was are a Pull request open for this. https://github.com/StaticCube/python-synology/pull/4

**Comment by StaticCube** [comment]
Didn't notice it either (mail is very full) will try to merge it asap.

**Comment by StaticCube** [comment]
Finally merged one of the PR's for https also created new pip file (version 0.2.0)
